title: Back Garden Trebuchet
hero_image: images/banner.JPG
description: Build your own back garden trebuchet
theme: blue # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 3 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: 
interests: ""
technologies: ""
site_areas:
steps:
  - title: Introduction
  - title: Amassing Materials
  - title: Building the Base
  - title: The Swing Arm

