---
title: Back Garden Trebuchet
hero_image: images/banner.JPG
description: Build your own back garden trebuchet
theme: blue
duration: 3
listed: false
ingredient: false
copyedit: false
curriculum:
interests: ''
technologies: ''
site_areas: HackSpace
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: Building the base
- title: The swing arm
- title: The ballast box
- title: The string and sling
- title: Fire!
  completion: internal
- title: More power
